### ISSUE TITLE
Support for the Classic Skype Website section

### ISSUE THREAD

**Issue by foxkehfan2328** [KonaloboStudio/konalobostudio.github.io#1]

**Comment by KonaloboStudio** [comment]
Work on the section has been halted temporarily.

**Comment by KonaloboStudio** [comment]
# The section is most likely closed permanently due to the lack of reasonability to support it further. Thank you all for using and supporting the project for a year and a half...

### _Also, if possible, please do not make forks of this section of the site._

# UPD 09.01.2025
I've decided to write one last time about my reasons for doing this, and (hopefully, unless I get a wild urge to) close this topic once and for all

### About the site itself:
at the moment the site is VERY outdated in terms of information, I don't have time to update it, and ONLY for the user system there is no point in keeping it up

Let me explain:

- Skype Classic Website news - updated “every 1,500 years”.
- The 8.x mods are dead because of Microsoft themselves, their changes to the clients, and the fact that I mistakenly deleted ALL clients from my Google Drive where they were stored. Of course, I still have Android clients and a couple of Windows client installers locally, but they need a lot of work due to the changes in the clients work.
- Archive of old Skype versions - Internet Archive has a much better archive of versions (there are almost all versions from 0.x to 7.x).
- The group system has not been used much since 2023, and the page itself needs to be updated very often, which I don't have time for.

### Why I do NOT want to see forks of this project (Classic Skype Website):
The site was made on a visual builder, changing it or adding pages manually (without using WYSIWYG project) is very difficult (in fact shitcode). It would be easier to just make a similar site from scratch than to modify my “creation”

_p.s I have little to do with this messenger, stop entering my TG and other chats exclusively for it._

**Comment by KonaloboStudio** [comment]
# UPD 28.02.2025

**All sources have been uploaded [here](https://github.com/KonaloboStudio/Base-of-Classic-Skype), you can do whatever you want with them**
